### ISSUE TITLE
ConcurrentTestCase doesn't work with JUnit's timeout support

### ISSUE THREAD

**Issue by flowersinthesand** [jhalterman/concurrentunit#9]
Here's a demo to reproduce the issue.
https://github.com/flowersinthesand/concurrentunit-junit-timeout-issue

Clone that repository and type `mvn test`. Then you will get:

```
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building issue-report 1.0.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ issue-report ---
[INFO] Deleting c:\Users\Donghwan\Documents\GitHub\concurrentunit-junit-issue\target
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ issue-report ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory c:\Users\Donghwan\Documents\GitHub\concurrentunit-junit-issue\src\main\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ issue-report ---
[INFO] No sources to compile
[INFO] 
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ issue-report ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory c:\Users\Donghwan\Documents\GitHub\concurrentunit-junit-issue\src\test\resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ issue-report ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to c:\Users\Donghwan\Documents\GitHub\concurrentunit-junit-issue\target\test-classes
[INFO] 
[INFO] --- maven-surefire-plugin:2.12.4:test (default-test) @ issue-report ---
[INFO] Surefire report directory: c:\Users\Donghwan\Documents\GitHub\concurrentunit-junit-issue\target\surefire-reports

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running DemoTest
on test1's await main
on test1's resume Thread-0
on test2's await Time-limited test
on test2's resume Thread-1
on test3's await Time-limited test
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.281 sec <<< FAILURE!
test3(DemoTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.IllegalStateException: Must be called from within the main test thread
	at net.jodah.concurrentunit.Waiter.await(Waiter.java:149)
	at net.jodah.concurrentunit.Waiter.await(Waiter.java:90)
	at net.jodah.concurrentunit.ConcurrentTestCase.await(ConcurrentTestCase.java:73)
	at DemoTest.test3(DemoTest.java:64)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.lang.Thread.run(Thread.java:745)


Results :

Tests in error: 
  test3(DemoTest): Must be called from within the main test thread

Tests run: 3, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.936 s
[INFO] Finished at: 2015-08-01T20:48:37+09:00
[INFO] Final Memory: 12M/163M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project issue-report: There are test failures.
[ERROR] 
[ERROR] Please refer to c:\Users\Donghwan\Documents\GitHub\concurrentunit-junit-issue\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

And here's the cause: https://github.com/flowersinthesand/concurrentunit-junit-timeout-issue/blob/master/src%2Ftest%2Fjava%2FDemoTest.java#L62-L63

As a workaround, I created a waiter per a test:
https://github.com/cettia/asity/blob/5bc9d2bc19e1916626426bb601f42e29ec3d87da/test/src/main/java/io/cettia/asity/test/support/ConcurrentTestBase.java#L13-L23

**Comment by jhalterman** [comment]
Thanks for reporting this. That main thread check was based on the assumption that test frameworks always call the test method from the same thread that they construct the test class with. Since that appears not to be true, the only thing I can really do is remove that check.

**Comment by jhalterman** [comment]
I haven't had a release in about a month - so I just pushed 0.4.1 with this change. :)

**Comment by flowersinthesand** [comment]
Thanks for the quick response and new release. I just updated it to 0.4.1 and had tests extend ConcurrentTestCase directly.

BTW, you may want to update https://github.com/jhalterman/concurrentunit/blob/master/CHANGES.md ;)
